# Generated by Django 5.2.11 on 2026-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_add_event_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="importance_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
