# Generated by Django 5.2.11 on 2026-02-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_category_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("wikidata_id", models.CharField(max_length=20, unique=True)),
                ("wikidata_url", models.URLField(blank=True, max_length=500)),
                ("instance_of", models.JSONField(blank=True, default=list)),
                ("subclass_of", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.category",
            ),
        ),
    ]
