# Generated by Django 5.2.11 on 2026-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_type_model_and_event_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="wikipedia_extract",
            field=models.TextField(blank=True),
        ),
    ]
