# Generated by Django 5.2.11 on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_created_updated_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTypeLoadProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_start", models.IntegerField()),
                ("year_end", models.IntegerField()),
                ("last_updated_at", models.DateTimeField()),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_progress",
                        to="events.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "event type load progress",
            },
        ),
        migrations.AddConstraint(
            model_name="eventtypeloadprogress",
            constraint=models.UniqueConstraint(
                fields=("event_type", "year_start", "year_end"),
                name="events_eventtypeloadprogress_unique_batch",
            ),
        ),
    ]
