# Generated by Django 5.2.11 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_type_load_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtypeloadprogress",
            name="events_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventtypeloadprogress",
            name="error_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
