# Generated by Django 5.2.11 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_type_cascade_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtypeloadprogress",
            name="events_updated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
